# Generated by Django 5.1.1 on 2024-09-17 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bookify', '0002_alter_book_isbn'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='book',
            table='inventory',
        ),
    ]
